In [45]:
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("skt/kobert-base-v1")
model = AutoModel.from_pretrained("skt/kobert-base-v1")

/home/sjlee/sj_virtual/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [46]:
A = tokenizer.encode('화학공학과')

In [47]:
B = tokenizer.encode('화학과')

In [48]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
B = pad_sequences([B],maxlen = len(A), padding = 'post')
B

2023-12-28 14:48:23.833303: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-28 14:48:24.552707: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


array([[517, 493,   0, 493,   0, 490,   0,   0,   0,   0,   0,   0,   0]],
      dtype=int32)

In [50]:
B = B.reshape(1,-1)

In [51]:
A = np.array(A).reshape(1,-1)
A

array([[517, 493,   0, 493,   0, 490,   0, 493,   0, 490,   0,   0,   0]])

In [52]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(A,B)

array([[0.82024647]])

In [57]:
C = tokenizer.encode('국어국문')
D = tokenizer.encode('물리')
if len(C)<len(D):
    C = pad_sequences([C],maxlen = len(D),padding = 'post')
    C = C.reshape(1,-1)
    D = np.array(D).reshape(1,-1)
else:
    D = pad_sequences([D],maxlen = len(C), padding = 'post')
    D = D.reshape(1,-1)
    C = np.array(C).reshape(1,-1)
cosine_similarity(C,D)

array([[0.37594894]])

In [53]:
import pandas as pd

In [70]:
consultant = pd.read_excel('./Consultant.xlsx')

In [71]:
consultant = consultant.set_index(keys = ['상담자 데이터 예시'])

In [72]:
consultant.columns = ['major','univ_name','company','company_sector','company_local']
consultant

major         univ_name           company  \
상담자 데이터 예시                                                           
1               산업공학과(label=4)  인천대학교(label = 0)  LG이노텍(label = 6)   
2               컴퓨터공학(label=0)  부산대학교(label = 2)    네이버(label = 1)   
3               화학공학과(label=1)  인천대학교(label = 0)  S-Oil(label = 2)   
4                 화학과(label=2)  서울대학교(label = 1)  \tSK (label = 3)   
5           신소재 공학과(label = 3)  서울대학교(label = 1)   현대제철(label = 5)   

           company_sector            company_local  
상담자 데이터 예시                                          
1                      IT    서울특별시 강서구 (label = 5)  
2                      IT  경기도 성남시 분당구 (label = 0)  
3                     에너지     서울특별시 마포구(label = 1)  
4                     에너지     서울특별시 종로구(label = 2)  
5                      소재      인천광역시 동구(label = 4)

In [73]:
import re
# (label=4) 제거
for cols in range(len(consultant)):
    for rows in range(len(consultant)):
        print(consultant.iloc[rows,cols])
        consultant.iloc[rows,cols] = re.sub(r'\({1}.+\){1}','',consultant.iloc[rows,cols])
        print(consultant.iloc[rows,cols])

산업공학과(label=4)
산업공학과
컴퓨터공학(label=0)
컴퓨터공학
화학공학과(label=1)
화학공학과
화학과(label=2)
화학과
신소재 공학과(label = 3)
신소재 공학과
인천대학교(label = 0)
인천대학교
부산대학교(label = 2)
부산대학교
인천대학교(label = 0)
인천대학교
서울대학교(label = 1)
서울대학교
서울대학교(label = 1)
서울대학교
LG이노텍(label = 6)
LG이노텍
네이버(label = 1)
네이버
S-Oil(label = 2)
S-Oil
	SK (label = 3)
	SK 
현대제철(label = 5)
현대제철
IT
IT
IT
IT
에너지
에너지
에너지
에너지
소재
소재
서울특별시 강서구 (label = 5)
서울특별시 강서구 
경기도 성남시 분당구 (label = 0)
경기도 성남시 분당구 
서울특별시 마포구(label = 1)
서울특별시 마포구
서울특별시 종로구(label = 2)
서울특별시 종로구
인천광역시 동구(label = 4)
인천광역시 동구


In [74]:
consultant

major univ_name company company_sector company_local
상담자 데이터 예시                                                        
1             산업공학과     인천대학교   LG이노텍             IT    서울특별시 강서구 
2             컴퓨터공학     부산대학교     네이버             IT  경기도 성남시 분당구 
3             화학공학과     인천대학교   S-Oil            에너지     서울특별시 마포구
4               화학과     서울대학교   \tSK             에너지     서울특별시 종로구
5           신소재 공학과     서울대학교    현대제철             소재      인천광역시 동구

In [75]:
consultant.iloc[3,2]=consultant.iloc[3,2].strip()

In [76]:
consultant

major univ_name company company_sector company_local
상담자 데이터 예시                                                        
1             산업공학과     인천대학교   LG이노텍             IT    서울특별시 강서구 
2             컴퓨터공학     부산대학교     네이버             IT  경기도 성남시 분당구 
3             화학공학과     인천대학교   S-Oil            에너지     서울특별시 마포구
4               화학과     서울대학교      SK            에너지     서울특별시 종로구
5           신소재 공학과     서울대학교    현대제철             소재      인천광역시 동구

In [31]:
user = pd.read_excel('./user.xlsx')
user

학생 데이터 예시           전공(major) 학교      (univ_name) 희망 회사 이름(hope_company)  \
0         1.0      컴퓨터공학(label=0)    인천대학교(label = 0)         카카오(label = 0)   
1         2.0      컴퓨터공학(label=0)    서울대학교(label = 1)         네이버(label = 1)   
2         3.0      화학공학과(label=1)    인천대학교(label = 0)       S-Oil(label = 2)   
3         4.0        화학과(label=2)    서울대학교(label = 1)       \tSK (label = 3)   
4         5.0  신소재 공학과(label = 3)    부산대학교(label = 2)        LG화학(label = 4)   
5         NaN                 NaN                 NaN                    NaN   
6         NaN                 NaN                 NaN                    NaN   
7         NaN                 NaN                 NaN                    NaN   
8         NaN                 NaN                 NaN                    NaN   
9         NaN                 NaN                 NaN                    NaN   
10        NaN                 NaN                 NaN                    NaN   
11        NaN                 NaN                 NaN                    NaN   
12        NaN                 NaN                 NaN                    NaN   
13        NaN                 NaN                 NaN                    NaN   
14        NaN                 NaN                 NaN                    NaN   
15        NaN                 NaN                 NaN                    NaN   
16        NaN                 NaN                 NaN                    NaN   
17        NaN                 NaN                 NaN                    NaN   
18        NaN                 NaN                 NaN                    NaN   
19        NaN                 NaN                 NaN                    NaN   
20        NaN                 NaN                 NaN                    NaN   
21        NaN                 NaN                 NaN                    NaN   
22        NaN                 NaN                 NaN                    NaN   
23        NaN                 NaN                                        NaN   

   희망 회사 업종(hope_company_sector) 희망 회사 지역(hope_company_local)  
0                             IT     경기도 성남시 분당구 (label = 0)   
1                             IT      경기도 성남시 분당구 (label = 0)  
2                            에너지         서울특별시 마포구(label = 1)  
3                            에너지         서울특별시 종로구(label = 2)  
4                             소재        서울특별시 영등포구(label = 3)  
5                            NaN                          NaN  
6                            NaN                          NaN  
7                            NaN                          NaN  
8                            NaN                          NaN  
9                            NaN                          NaN  
10                           NaN                          NaN  
11                           NaN                          NaN  
12                           NaN                          NaN  
13                           NaN                          NaN  
14                           NaN                          NaN  
15                           NaN                          NaN  
16                           NaN                          NaN  
17                           NaN                          NaN  
18                           NaN                          NaN  
19                           NaN                          NaN  
20                           NaN                          NaN  
21                           NaN                          NaN  
22                           NaN                          NaN  
23                           NaN                          NaN

In [32]:
user = user.dropna(axis = 0)
user

학생 데이터 예시           전공(major) 학교      (univ_name) 희망 회사 이름(hope_company)  \
0        1.0      컴퓨터공학(label=0)    인천대학교(label = 0)         카카오(label = 0)   
1        2.0      컴퓨터공학(label=0)    서울대학교(label = 1)         네이버(label = 1)   
2        3.0      화학공학과(label=1)    인천대학교(label = 0)       S-Oil(label = 2)   
3        4.0        화학과(label=2)    서울대학교(label = 1)       \tSK (label = 3)   
4        5.0  신소재 공학과(label = 3)    부산대학교(label = 2)        LG화학(label = 4)   

  희망 회사 업종(hope_company_sector) 희망 회사 지역(hope_company_local)  
0                            IT     경기도 성남시 분당구 (label = 0)   
1                            IT      경기도 성남시 분당구 (label = 0)  
2                           에너지         서울특별시 마포구(label = 1)  
3                           에너지         서울특별시 종로구(label = 2)  
4                            소재        서울특별시 영등포구(label = 3)

In [35]:
user = user.set_index(keys = ['학생 데이터 예시'])
user

전공(major) 학교      (univ_name) 희망 회사 이름(hope_company)  \
학생 데이터 예시                                                                  
1.0            컴퓨터공학(label=0)    인천대학교(label = 0)         카카오(label = 0)   
2.0            컴퓨터공학(label=0)    서울대학교(label = 1)         네이버(label = 1)   
3.0            화학공학과(label=1)    인천대학교(label = 0)       S-Oil(label = 2)   
4.0              화학과(label=2)    서울대학교(label = 1)       \tSK (label = 3)   
5.0        신소재 공학과(label = 3)    부산대학교(label = 2)        LG화학(label = 4)   

          희망 회사 업종(hope_company_sector) 희망 회사 지역(hope_company_local)  
학생 데이터 예시                                                             
1.0                                  IT     경기도 성남시 분당구 (label = 0)   
2.0                                  IT      경기도 성남시 분당구 (label = 0)  
3.0                                 에너지         서울특별시 마포구(label = 1)  
4.0                                 에너지         서울특별시 종로구(label = 2)  
5.0                                  소재        서울특별시 영등포구(label = 3)

In [37]:
user.index = [1,2,3,4,5]

In [41]:
user.columns = ['major','univ_name','company','company_sector','company_local']
user

major         univ_name           company company_sector  \
1      컴퓨터공학(label=0)  인천대학교(label = 0)    카카오(label = 0)             IT   
2      컴퓨터공학(label=0)  서울대학교(label = 1)    네이버(label = 1)             IT   
3      화학공학과(label=1)  인천대학교(label = 0)  S-Oil(label = 2)            에너지   
4        화학과(label=2)  서울대학교(label = 1)  \tSK (label = 3)            에너지   
5  신소재 공학과(label = 3)  부산대학교(label = 2)   LG화학(label = 4)             소재   

              company_local  
1  경기도 성남시 분당구 (label = 0)   
2   경기도 성남시 분당구 (label = 0)  
3      서울특별시 마포구(label = 1)  
4      서울특별시 종로구(label = 2)  
5     서울특별시 영등포구(label = 3)

In [42]:
import re
# (label=4) 제거
for cols in range(len(consultant)):
    for rows in range(len(consultant)):
        print(user.iloc[rows,cols])
        user.iloc[rows,cols] = re.sub(r'\({1}.+\){1}','',user.iloc[rows,cols])
        print(user.iloc[rows,cols])

컴퓨터공학(label=0)
컴퓨터공학
컴퓨터공학(label=0)
컴퓨터공학
화학공학과(label=1)
화학공학과
화학과(label=2)
화학과
신소재 공학과(label = 3)
신소재 공학과
인천대학교(label = 0)
인천대학교
서울대학교(label = 1)
서울대학교
인천대학교(label = 0)
인천대학교
서울대학교(label = 1)
서울대학교
부산대학교(label = 2)
부산대학교
카카오(label = 0)
카카오
네이버(label = 1)
네이버
S-Oil(label = 2)
S-Oil
	SK (label = 3)
	SK 
LG화학(label = 4)
LG화학
IT
IT
IT
IT
에너지
에너지
에너지
에너지
소재
소재
경기도 성남시 분당구 (label = 0) 
경기도 성남시 분당구  
경기도 성남시 분당구 (label = 0)
경기도 성남시 분당구 
서울특별시 마포구(label = 1)
서울특별시 마포구
서울특별시 종로구(label = 2)
서울특별시 종로구
서울특별시 영등포구(label = 3)
서울특별시 영등포구


In [63]:
user

major univ_name company company_sector  company_local
1    컴퓨터공학     인천대학교     카카오             IT  경기도 성남시 분당구  
2    컴퓨터공학     서울대학교     네이버             IT   경기도 성남시 분당구 
3    화학공학과     인천대학교   S-Oil            에너지      서울특별시 마포구
4      화학과     서울대학교   \tSK             에너지      서울특별시 종로구
5  신소재 공학과     부산대학교    LG화학             소재     서울특별시 영등포구

In [77]:
user.index.name = "학생 데이터 예시"
user

major univ_name company company_sector  company_local
학생 데이터 예시                                                         
1            컴퓨터공학     인천대학교     카카오             IT  경기도 성남시 분당구  
2            컴퓨터공학     서울대학교     네이버             IT   경기도 성남시 분당구 
3            화학공학과     인천대학교   S-Oil            에너지      서울특별시 마포구
4              화학과     서울대학교   \tSK             에너지      서울특별시 종로구
5          신소재 공학과     부산대학교    LG화학             소재     서울특별시 영등포구

In [78]:
consultant

major univ_name company company_sector company_local
상담자 데이터 예시                                                        
1             산업공학과     인천대학교   LG이노텍             IT    서울특별시 강서구 
2             컴퓨터공학     부산대학교     네이버             IT  경기도 성남시 분당구 
3             화학공학과     인천대학교   S-Oil            에너지     서울특별시 마포구
4               화학과     서울대학교      SK            에너지     서울특별시 종로구
5           신소재 공학과     서울대학교    현대제철             소재      인천광역시 동구

In [82]:
tokenizer.encode('SK')

[689, 0, 0]

In [83]:
C = tokenizer.encode('LG이노텍')
D = tokenizer.encode('네이버')
if len(C)<len(D):
    C = pad_sequences([C],maxlen = len(D),padding = 'post')
    C = C.reshape(1,-1)
    D = np.array(D).reshape(1,-1)
else:
    D = pad_sequences([D],maxlen = len(C), padding = 'post')
    D = D.reshape(1,-1)
    C = np.array(C).reshape(1,-1)
cosine_similarity(C,D)

array([[0.70231244]])

In [84]:
C = tokenizer.encode('LG이노텍')
D = tokenizer.encode('S-Oil')
if len(C)<len(D):
    C = pad_sequences([C],maxlen = len(D),padding = 'post')
    C = C.reshape(1,-1)
    D = np.array(D).reshape(1,-1)
else:
    D = pad_sequences([D],maxlen = len(C), padding = 'post')
    D = D.reshape(1,-1)
    C = np.array(C).reshape(1,-1)
cosine_similarity(C,D)

array([[0.77174598]])

In [85]:
C = tokenizer.encode('LG이노텍')
D = tokenizer.encode('SK')
if len(C)<len(D):
    C = pad_sequences([C],maxlen = len(D),padding = 'post')
    C = C.reshape(1,-1)
    D = np.array(D).reshape(1,-1)
else:
    D = pad_sequences([D],maxlen = len(C), padding = 'post')
    D = D.reshape(1,-1)
    C = np.array(C).reshape(1,-1)
cosine_similarity(C,D)

array([[0.69218487]])

### 결과 1: 회사 이름 까지는 Tokenize했을때 잘 반영 못하는 거 같다
-> 잘 반영이 되는 major와 company_sector 만을 토크나이즈 하는 것을 타겟으로 하자

In [92]:
C = tokenizer.encode('서울특별시 마포구')
D = tokenizer.encode('서울특별시 영등포구')
if len(C)<len(D):
    C = pad_sequences([C],maxlen = len(D),padding = 'post')
    C = C.reshape(1,-1)
    D = np.array(D).reshape(1,-1)
else:
    D = pad_sequences([D],maxlen = len(C), padding = 'post')
    D = D.reshape(1,-1)
    C = np.array(C).reshape(1,-1)
cosine_similarity(C,D)

array([[0.74156281]])

In [93]:
C = tokenizer.encode('서울특별시 마포구')
D = tokenizer.encode('서울특별시 종로구')
if len(C)<len(D):
    C = pad_sequences([C],maxlen = len(D),padding = 'post')
    C = C.reshape(1,-1)
    D = np.array(D).reshape(1,-1)
else:
    D = pad_sequences([D],maxlen = len(C), padding = 'post')
    D = D.reshape(1,-1)
    C = np.array(C).reshape(1,-1)
cosine_similarity(C,D)

array([[1.]])

In [95]:
C = tokenizer.encode('서울특별시 마포구')
D = tokenizer.encode('서울특별시 강서구')
if len(C)<len(D):
    C = pad_sequences([C],maxlen = len(D),padding = 'post')
    C = C.reshape(1,-1)
    D = np.array(D).reshape(1,-1)
else:
    D = pad_sequences([D],maxlen = len(C), padding = 'post')
    D = D.reshape(1,-1)
    C = np.array(C).reshape(1,-1)
cosine_similarity(C,D)

array([[0.74180528]])

In [94]:
C = tokenizer.encode('서울특별시 마포구')
D = tokenizer.encode('경기도 성남시 분당구')
if len(C)<len(D):
    C = pad_sequences([C],maxlen = len(D),padding = 'post')
    C = C.reshape(1,-1)
    D = np.array(D).reshape(1,-1)
else:
    D = pad_sequences([D],maxlen = len(C), padding = 'post')
    D = D.reshape(1,-1)
    C = np.array(C).reshape(1,-1)
cosine_similarity(C,D)

array([[0.32130926]])

### 결과2: 서울특별시 와 경기도는 잘 구분할 수 있는걸 볼 수 있지만 서울시 내에서는 잘 구분하지 못함

## 추천시스템의 설계
1. 일차적으로 회사이름과 직무가 맞는 사람들을 단순 필터링 한다.(가장 우선순위)<br><br>
2. 일차에서 필터링 한 사람들을 대상으로 회사의 섹터, 전공은 코사인 유사도로 나머지 Label encoding된 변수들은 맞는 것들의 카운트를 통해서 우선순위를 정한다.<br><br>
3. 업데이트를 하게되면 그 다음 우선순위인 사람들을 추천하게 된다.

* 기본적으로 IBCF UBCF는 적합하지 않다.

In [139]:
C = tokenizer.encode('에너지')
D = tokenizer.encode('소재')
if len(C)<len(D):
    C = pad_sequences([C],maxlen = len(D),padding = 'pre')
    C = C.reshape(1,-1)
    D = np.array(D).reshape(1,-1)
else:
    D = pad_sequences([D],maxlen = len(C), padding = 'pre')
    D = D.reshape(1,-1)
    C = np.array(C).reshape(1,-1)
cosine_similarity(C,D)

array([[0.]])

In [138]:
user2 = user.drop(columns = ['company'])
consultant2 = consultant.drop(columns = ['company'])

In [87]:
user2

major univ_name company_sector  company_local
학생 데이터 예시                                                 
1            컴퓨터공학     인천대학교             IT  경기도 성남시 분당구  
2            컴퓨터공학     서울대학교             IT   경기도 성남시 분당구 
3            화학공학과     인천대학교            에너지      서울특별시 마포구
4              화학과     서울대학교            에너지      서울특별시 종로구
5          신소재 공학과     부산대학교             소재     서울특별시 영등포구

In [88]:
consultant2

major univ_name company_sector company_local
상담자 데이터 예시                                                
1             산업공학과     인천대학교             IT    서울특별시 강서구 
2             컴퓨터공학     부산대학교             IT  경기도 성남시 분당구 
3             화학공학과     인천대학교            에너지     서울특별시 마포구
4               화학과     서울대학교            에너지     서울특별시 종로구
5           신소재 공학과     서울대학교             소재      인천광역시 동구