In [3]:
from gensim.models import FastText

# 모델 파일 경로 혹은 모델 이름 (ex: 'cc.en.300.bin')
model = FastText.load_fasttext_format('./ft.morpheme.char.w+namu+nsmc.bin')
model

/tmp/ipykernel_1737561/2002691168.py:4: DeprecationWarning: Call to deprecated `load_fasttext_format` (use load_facebook_vectors (to use pretrained embeddings) or load_facebook_model (to continue training with the loaded full model, more RAM) instead).
  model = FastText.load_fasttext_format('./ft.morpheme.char.w+namu+nsmc.bin')


In [4]:
from sklearn.metrics.pairwise import cosine_similarity

In [68]:
A = model.wv['문구용품음반등도소매업']
B = model.wv['석유개발 및 기타사업 석유사업 윤활유사업 화학사업']
C = model.wv['석유화학계 기초 화학물질 제조업']
D = model.wv['도서의도소매업,출판업외']

In [64]:
cosine_similarity(A.reshape(1,-1),B.reshape(1,-1))

array([[0.54551363]], dtype=float32)

In [65]:
cosine_similarity(B.reshape(1,-1),C.reshape(1,-1))

array([[0.8265423]], dtype=float32)

In [69]:
cosine_similarity(A.reshape(1,-1),D.reshape(1,-1))

array([[0.5785236]], dtype=float32)