In [127]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel, AdamW

# KcBERT 모델과 토크나이저 로드
model_name = "beomi/kcbert-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name,output_hidden_states = True)

In [13]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics.pairwise import cosine_similarity

In [163]:
C = tokenizer.encode('화학공학과')
D = tokenizer.encode('신소재공학과')
if len(C)<len(D):
    C = pad_sequences([C],maxlen = len(D),padding = 'post')
    C = C.reshape(-1)
    D = np.array(D).reshape(-1)
    token_ids = torch.tensor(C).unsqueeze(0)
    A = model(token_ids)
    token_ids = torch.tensor(D).unsqueeze(0)
    B = model(token_ids)
else:
    D = pad_sequences([D],maxlen = len(C), padding = 'post')
    D = D.reshape(-1)
    C = np.array(C).reshape(-1)
    token_ids = torch.tensor(C).unsqueeze(0)
    A = model(token_ids)
    token_ids = torch.tensor(D).unsqueeze(0)
    B = model(token_ids)
cosine_similarity(A['last_hidden_state'].view(1,-1).detach().numpy(),B['last_hidden_state'].view(1,-1).detach().numpy())

array([[0.3361916]], dtype=float32)

In [142]:
A

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.1716, -0.9146,  0.5384,  ...,  1.2032,  0.4898,  0.0408],
         [ 1.2688,  0.5635,  1.3659,  ...,  0.3163, -0.2925, -0.5940],
         [-1.4623, -0.5174,  0.0718,  ..., -0.5063,  0.6069, -0.3315],
         [-0.7975, -0.0125,  1.1376,  ..., -0.0942, -0.0225,  0.6562],
         [ 0.8180,  1.0092,  2.1360,  ...,  0.1704, -0.3273, -0.5627]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-0.9748,  0.1829,  0.4880,  0.2070, -0.7033,  0.9815,  0.1433, -0.8346,
         -0.6689, -0.2150,  0.6789, -0.5322,  0.0516, -0.5703, -0.1850, -0.9468,
          0.9749,  0.1620,  0.1247, -0.1089,  0.3395, -0.9065, -0.2862,  0.4513,
         -0.9896, -0.1575,  0.1764,  0.5577, -0.0704,  0.0269, -0.2526, -0.8797,
          0.5610,  0.4424, -0.9111, -0.7021,  0.5003, -0.3672,  0.2924,  0.1297,
          0.1030,  0.2123,  0.5662, -0.9888,  0.9902, -0.0125,  0.3285,  0.6919,
         -0.9803, -0.5511,  0.1224, 

In [ ]:
token_ids = torch.tensor(C).unsqueeze(0)

A = model(token_ids)

In [133]:
C = tokenizer.encode('화학과',max_length = 5,padding = True)
C

[2, 22190, 4128, 3]

In [134]:
token_ids = torch.tensor(C).unsqueeze(0)

In [135]:
token_ids

tensor([[    2, 22190,  4128,     3]])

In [136]:
A = model(token_ids)

In [137]:
A['last_hidden_state'].size()

torch.Size([1, 4, 768])

In [138]:
C = tokenizer.encode('화학공학과')
C

token_ids = torch.tensor(C).unsqueeze(0)

token_ids

A = model(token_ids)

A['last_hidden_state'].size()

torch.Size([1, 5, 768])

In [176]:
from gensim.models.keyedvectors import KeyedVectors
model = KeyedVectors.load_word2vec_format('./wiki.ko.vec')

In [181]:
C = model['화학공학과']

In [182]:
C.shape

(300,)

In [178]:
D = model['화학과']

In [180]:
D.shape

(300,)

In [184]:
from sklearn.metrics.pairwise import cosine_similarity

In [274]:
from gensim.models.fasttext import load_facebook_model
model = load_facebook_model('./cc.en.300.bin')

In [275]:
model.wv['Front-End developer']

array([-3.03040817e-02, -5.96988807e-03,  3.26460693e-03,  6.45621791e-02,
       -2.72143707e-02, -1.03784110e-02, -2.85519641e-02,  1.43894029e-03,
        9.38140508e-03, -8.67239386e-03,  4.86782938e-03, -1.04308315e-02,
        9.69011337e-03,  2.37070047e-03,  1.14029702e-02,  4.60887561e-03,
        1.84130557e-02,  8.82854313e-03, -1.20033221e-02,  5.57404272e-02,
       -1.14240348e-02,  1.14665106e-02, -1.30961742e-02,  3.19548347e-03,
        3.25945914e-02,  4.98185754e-02, -8.08714982e-03,  1.89191531e-02,
        3.63499932e-02,  3.88517007e-02, -2.29974426e-02, -7.86866248e-03,
        3.08546256e-02,  1.00257760e-02, -9.17846221e-04, -2.25267224e-02,
        9.99095570e-03,  3.13309976e-03,  1.31459450e-02,  9.22300760e-03,
       -2.30779424e-02, -1.02767791e-03,  1.59687945e-03, -1.36061488e-02,
        6.80105761e-03,  1.48917818e-02,  1.40220122e-02,  8.53330456e-03,
       -4.13198257e-03, -1.51965357e-02, -1.57321338e-02, -2.26063468e-02,
        7.66295381e-03, -

In [310]:
C = model.wv['Front-End developer']
D = model.wv['Back-End developer']
cosine_similarity(C.reshape(1,-1),D.reshape(1,-1))

array([[0.8822187]], dtype=float32)

In [311]:
C = model.wv['Front-End developer']
D = model.wv['Server developer']
cosine_similarity(C.reshape(1,-1),D.reshape(1,-1))

array([[0.47927618]], dtype=float32)

In [312]:
C = model.wv['Back-End developer']
D = model.wv['Server developer']
cosine_similarity(C.reshape(1,-1),D.reshape(1,-1))

array([[0.46573743]], dtype=float32)

In [292]:
C = model.wv['Chemistry']
D = model.wv['Chemical Engineering']
cosine_similarity(C.reshape(1,-1),D.reshape(1,-1))

array([[0.3122827]], dtype=float32)

In [290]:
C = model.wv['Chemistry']
D = model.wv['Economics']
cosine_similarity(C.reshape(1,-1),D.reshape(1,-1))

array([[0.5039709]], dtype=float32)

In [297]:
C = model.wv['Computer Engineering']
D = model.wv['Mathematics']
cosine_similarity(C.reshape(1,-1),D.reshape(1,-1))

array([[0.2558936]], dtype=float32)

In [303]:
C = model.wv['Computer Engineering']
D = model.wv['Data Science']
cosine_similarity(C.reshape(1,-1),D.reshape(1,-1))

array([[0.5996271]], dtype=float32)

In [304]:
C = model.wv['Statistics']
D = model.wv['Mathematics']
cosine_similarity(C.reshape(1,-1),D.reshape(1,-1))

array([[0.46231645]], dtype=float32)

In [321]:
C = model.wv['Data Science']
D = model.wv['Mathematics']
cosine_similarity(C.reshape(1,-1),D.reshape(1,-1))

array([[0.23061872]], dtype=float32)

In [1]:
import pandas as pd

In [11]:
major = pd.read_csv('./korean_major.csv')

In [12]:
major

major                                            explain
0         경호학과  범죄 문제는 국민의 안전과 직결되고 삶의 질을 평가하는 기준이 되지만, 범죄가 늘면...
1        한국어학과  한국어는 한국의 공용어로서, 한국 민족이 현재 주로 한반도 전역과 제주도를 비롯한 ...
2         한국어과  한국어과는 외국인 및 동포 유학생들을 대상으로 한국어와 한국문화를 익히고 전문적인 ...
3         동양화과  동양화과는 동양사상을 바탕으로 전통과 혁신이 공존하는 새로운 동양화 분야를 창출하고...
4       공업디자인과  우리에게 익숙한 스마트폰부터 낯선 항공우주 기기들까지 우리가 사용하고, 이용하는 제...
..         ...                                                ...
497  모바일시스템공학과  스마트폰, 스마트워치, 태블릿PC 쉽게 들고 다닐수 있는 장치가 바로 모바일 기기라...
498    목조형가구학과  나무는 인류 발생 초기부터 생활도구의 재료이었습니다. 책상, 의자, 탁자, 그 밖의...
499        무도과  무도는 무예 및 무술을 통틀어 이르는 말인데요. 무기 쓰기, 주먹질, 발길질, 말달...
500       무도학과  무도학은 전통 무예사상을 바탕으로 무도에 관한 학문 연구 및 그 응용 방법을 연구하...
501        무용과  우리는 손짓, 몸짓을 통하여 감정을 표현하기도 하죠? 무용은 우리 몸의 다양한 움직...

[502 rows x 2 columns]