In [1]:
import tensorflow as tf
from transformers import AutoTokenizer
from transformers import TFGPT2LMHeadModel

2023-12-06 22:21:15.781125: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-06 22:21:16.316634: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/sjlee/sj_virtual/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
tokenizer = AutoTokenizer.from_pretrained('skt/kogpt2-base-v2')
model = TFGPT2LMHeadModel.from_pretrained('skt/kogpt2-base-v2',from_pt = True)

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2023-12-06 22:21:20.903797: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-12-06 22:21:20.905925: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFGPT2LMHeadModel: ['transformer.h.7.attn.masked_bias', 'lm_head.

In [3]:
sent = '건강한 몸을 만들기 위해서는' 

In [4]:
input_ids = tokenizer.tokenize(sent) ### ... 이 부분을 완성하시오
print(input_ids) ### ... 이 부분을 완성하시오

['▁건강한', '▁몸을', '▁만들기', '▁위해서는']


In [7]:
input_ids = tokenizer.encode(sent) ### ... 이 부분을 완성하시오
print(input_ids)
input_ids = tf.convert_to_tensor([input_ids])
print(input_ids) ### ... 이 부분을 완성하시오

[22159, 14226, 15381, 11357]
tf.Tensor([[22159 14226 15381 11357]], shape=(1, 4), dtype=int32)


In [8]:
output = model.generate(input_ids,
                   max_length=128,
                   repetition_penalty=2.0) ### ... 이 부분을 완성하시오
print(output)
output_ids = output.numpy().tolist()[0]
print(output_ids) ### ... 이 부분을 완성하시오

tf.Tensor(
[[22159 14226 15381 11357 23879 39306 25235  9376 33820 10362  9430 15967
  38594 12443  8137 17764  9033  9199 15177 26421   387 15386   409  7162
   9346  7071 11913  9091  9377 12486 10108 24873  7198  9391 37611  9676
  14458  9492 20305 10090 10254  9178  7335  8704 41845 18418  9277 18324
   8643  7122  8135  9351 16709 10335 18380 16286 13940 19671  9048 18281
   8648 44869  6824 12923 13600  9600 39137  8066 23865  8470 10461  9164
   7609  8397  9225  9029 45837  9052 48276 15528 10386 10988  8711 22452
   8765 27929 12972 12364 23511  8450 16803 21302  6903  9410 13041 25606
  49019  7586  9752  8143 10850 10007 26006 27147  8146 26523  9359  9341
  13219 35943 14441  8000 13532 13565 11634 12268 10279 36122  9960  8405
  11545 13235  7849 17304 14355 10826 43075  7235]], shape=(1, 128), dtype=int32)
[22159, 14226, 15381, 11357, 23879, 39306, 25235, 9376, 33820, 10362, 9430, 15967, 38594, 12443, 8137, 17764, 9033, 9199, 15177, 26421, 387, 15386, 409, 7162, 9346, 70

In [7]:
tokenizer.decode(output_ids)

'건강한 몸을 만들기 위해서는 무엇보다 규칙적인 운동과 식이요법을 통해 균형 잡힌 영양을 섭취하는 것이 중요하다.\n특히, 비타민C는 체내 에너지 생성을 촉진시켜 신진대사를 원활하게 하고 면역력을 높여주는 역할을 한다.\n또한 항산화 작용을 하는 폴리페놀은 우리 몸의 세포막을 구성하는 필수 성분이다.\n폴리펩타이드가 풍부한 식품으로는 토마토와 브로콜리, 양배추 등이 있다.\n토마토에는 식이섬유소가 풍부해 피로회복에 도움을 준다.\n브로컬리에는 칼슘과 철분이 풍부하다.\n비타민 C의 흡수를 돕는 칼륨이 풍부하게 들어 있어 뼈 건강에 좋다.\n양파는 섬유질이 많아 혈압을 낮춰주고 혈액순환을 도와준다.\n마늘도'

In [9]:
input_ids

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[22159, 14226, 15381, 11357]], dtype=int32)>

In [14]:
sent = '건강한 몸을 만들기 위해서는' 
input_ids = tokenizer.encode(sent) ### ... 이 부분을 완성하시오

In [15]:
input_ids

[22159, 14226, 15381, 11357]

In [16]:
import numpy as np
output = model(np.array(input_ids))
output

TFCausalLMOutputWithCrossAttentions(loss=None, logits=<tf.Tensor: shape=(1, 4, 51200), dtype=float32, numpy=
array([[[-6.159606  , -5.6269407 , -5.299073  , ...,  0.18111056,
         -4.966686  , -3.0936298 ],
        [-4.6646914 , -5.924713  , -4.8221283 , ...,  2.4812737 ,
         -3.5151503 ,  2.3900409 ],
        [-5.085369  , -4.0964813 , -6.0712814 , ...,  1.1920149 ,
         -2.9018319 , -3.3687854 ],
        [-6.204307  , -6.28462   , -6.3270826 , ...,  1.8252177 ,
         -3.9164736 , -2.7165346 ]]], dtype=float32)>, past_key_values=(<tf.Tensor: shape=(2, 1, 12, 4, 64), dtype=float32, numpy=
array([[[[[-7.66822994e-01,  9.92477775e-01, -7.21697927e-01, ...,
           -7.51046181e-01, -9.66639698e-01, -3.85684848e-01],
          [ 1.84529405e-02,  3.34385538e+00, -1.25435460e+00, ...,
           -1.68122625e+00, -1.89542043e+00, -8.23476732e-01],
          [-8.48053157e-01,  2.50739455e+00, -1.50371182e+00, ...,
           -1.53229165e+00, -9.12304699e-01, -4.63684142e-01]

In [9]:
output.logits

<tf.Tensor: shape=(1, 4, 51200), dtype=float32, numpy=
array([[[-6.159606  , -5.6269407 , -5.299073  , ...,  0.18111056,
         -4.966686  , -3.0936298 ],
        [-4.6646914 , -5.924713  , -4.8221283 , ...,  2.4812737 ,
         -3.5151503 ,  2.3900409 ],
        [-5.085369  , -4.0964813 , -6.0712814 , ...,  1.1920149 ,
         -2.9018319 , -3.3687854 ],
        [-6.204307  , -6.28462   , -6.3270826 , ...,  1.8252177 ,
         -3.9164736 , -2.7165346 ]]], dtype=float32)>

In [10]:
output.logits.shape

TensorShape([1, 4, 51200])

In [11]:
top5 = tf.math.top_k(output.logits[0,-1],k = 5)

In [12]:
top5

TopKV2(values=<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([10.895336 , 10.395889 ,  9.9456415,  9.840967 ,  9.83118  ],
      dtype=float32)>, indices=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([23879, 22159, 20030, 11342, 39306], dtype=int32)>)

In [13]:
tokenizer.convert_ids_to_tokens(top5.indices.numpy())

['▁무엇보다', '▁건강한', '▁무엇보다도', '▁건강', '▁규칙적인']

In [14]:
top5.indices.numpy() # value는 log

array([23879, 22159, 20030, 11342, 39306], dtype=int32)

In [15]:
sent = '건강한 몸을 만들기 위해서는' 
input_ids = tokenizer.encode(sent) 

In [16]:
import random

while len(input_ids) < 50:
    output = model(np.array([input_ids]))
    top5 = tf.math.top_k(output.logits[0, -1], k=5)
    token_id = random.choice(top5.indices.numpy())
    input_ids.append(token_id)

In [17]:
input_ids

[22159,
 14226,
 15381,
 11357,
 11342,
 9038,
 27343,
 10541,
 14226,
 9945,
 18566,
 9031,
 9322,
 15177,
 7335,
 22418,
 39306,
 13579,
 9277,
 10599,
 10586,
 21292,
 18988,
 25998,
 9326,
 16653,
 25998,
 9326,
 8765,
 9465,
 9178,
 18988,
 32030,
 10134,
 9036,
 25940,
 9277,
 10599,
 37428,
 32030,
 26774,
 16364,
 27290,
 10599,
 48512,
 11764,
 9337,
 14970,
 9346,
 14116]

In [18]:
tokenizer.decode(input_ids)

'건강한 몸을 만들기 위해서는 건강하고 탄력 있게 몸을 관리해주는 것 또한 중요하다.\n또한, 규칙적인 운동을 하는 것도 좋은 방법이다.\n운동은 하루에 20분, 하루에 20회 정도 한다.\n운동은 30분마다 한 번씩 하는 것도 좋고, 30분 간격으로 꾸준히 해주는 것도 효과적이다.\n운동을 할 때마다 체내에'

# pipeline을 이용해 문장 생성해보기

In [19]:
from transformers import pipeline
pipe = pipeline("text-generation",model = "skt/kogpt2-base-v2",device = 0)

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


In [20]:
sent = "건강한 몸을 만들기 위해서는"
generated_text = pipe(sent)

/home/sjlee/sj_virtual/lib/python3.8/site-packages/transformers/generation/utils.py:1369: UserWarning: Using `max_length`'s default (50) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


In [21]:
generated_text

[{'generated_text': '건강한 몸을 만들기 위해서는 운동과 식이요법, 스트레스, 수면시간 조절 등 다양한 방법을 활용하면 도움이 된다.\n또한 규칙적인 생활을 통해 스트레스와 긴장을 줄이고, 수면을 통해 신체의 균형을 맞춰주는 것도 필수다.\n운동을 통해 균형점을 찾고, 스트레스를 해소하는'}]

In [22]:
sent = "건강한 몸을 만들기 위해서는"
generated_text = pipe(sent,max_new_tokens = 256)

In [23]:
generated_text

[{'generated_text': '건강한 몸을 만들기 위해서는 체내 노폐물을 제거하는 데 초점을 맞춰야 하며, 특히 스트레스를 주는 음식은 피하고 단백질과 비타민이 잘 포함된 음식을 섭취하는 게 좋다.\n또한 매일 같은 반찬에 든 육류와 유제품을 되도록 적게 먹고, 저녁식사도 규칙적으로 하는 노력이 중요하다고 전문가들은 지적한다.\n또한 탄수화물과 단백질 섭취가 낮을수록 비타민이 많이 함유된 음식을 꾸준히 섭취하는 게 좋다. 경기침체가 지속될 경우 내년 우리나라 실질경제성장률이 -2%대 수준에 그칠 것이라는 전망이 나왔다.\n국제통화기금(IMF)은 2일 국내총생산(GDP) 대비 내년 실질경제성장률을 -3.2~2.3%로 예측하고 있다.\n이 전망치는 IMF가 지난 8월 우리나라 성장률 전망을 -4.5%로 낮춰 잡은 이후 5개월만에 다시 수정한 것이다.\n이날 공개된 세계증권예탁증서(ADR) 시장 동향 보고서인 ‘2018 아시아-태평양 지역 투자자 전망보고서’에 따르면 전 세계 증권시장에서 거래되는 ADR은 올해 12월 현재 4190억달러에 달해 내년 실질 GDP 성장률 전망치(1.8%)를 1.0%포인트 웃돌 것으로 전망된다.\nADR은 국제유가의 상승세와 미국 경기 회복에 따라 금융 시장에서의 순유입 전망치인 10%를 크게 웃돌고, 투자심리 역시 양호한 모습을 보이고 있다.\n'}]

In [24]:
len(generated_text[0]['generated_text'].split())

142

In [25]:
sent = '건강한 몸을 만들기 위해서는 어떻게 해야 돼?'  ### ... 이 부분을 완성하시오
generated_text = pipe(sent, max_new_tokens=256)
print(generated_text[0]['generated_text'])

건강한 몸을 만들기 위해서는 어떻게 해야 돼? 이 두 가지 방법으로만 해결되지 않으면 안 되고 뭔가를 해보려고 하는 노력을 게을리 해서는 안 된다. 미국 정부의 한 소식통은 28일 북한과 미국이 6자회담 차원에서 논의하고 있다고 밝힌 것과 관련, “북한이 6자 회담 수석대표 회담 제의를 받아들였을 가능성도 배제하지 않고 있다”며 “미국은 북핵 6자 회담이 조속히 개막되기를 희망하고 있고 한국 대통령도 이런 뜻을 거듭 확인했다”고 밝혔다.
이는 오바마 행정부의 방북이 북한의 6자 회담 복귀로 이어질 수 있을지 여부에 관심을 집중시키는 한편 미국 측의 6자 회담 관련 협의 의지도 강하게 시사하는 대목이다.
이 소식통은 “이날 6자회담 수석대표 회담이 열릴 것으로 기대했지만 북측은 이날 회담과 관련 언급조차 하지 않았다”며 “회담 재개 여부는 미국이 결정할 일이며 회담 개최 가능성은 남아 있는 셈"이라고 지적했다.
그는 “한국 정부가 최근 북 핵 문제의 평화적 해결과 한반도의 비핵화라는 기치를 내걸었다”며 “이번 회담이 6자 회담에 대한 새로운 결의를 마련하는 계기가 될 수도 있을 것”이라고 덧붙였다.
이 소식통은 “6자 회담이 재개될 가능성도 있다는 점을 분명히 한 것”이라며 “북한은 아직 6자회담을 원하지만 미국이 대북 메시지를 갖고 있을 경우 그 답변을 기다리고 있을 것”이라고 말했다.
그는 “


In [26]:
sent = "안녕하세요"
generated_text = pipe(sent, max_new_tokens=256)
print(generated_text[0]['generated_text'])

안녕하세요’라는 물음에 아빠는 “지금까지 아이와 함께해본 적은 없었어요, 아빠가 잘 해주려고, 제 손을 잡아주시고, 엄마가 도와줬거든요”라고 대답했다고 한다.
아이가 태어난 지 3일째 되던 날, 아빠는 “지난해 2월 아이가 태어났어요. 그런데 지금까지 아이가 아프다, 아프다는 얘길 듣고 어떻게 해. 아프지 않더라도 우리 가족은 건강하게 살 거예요”라고 말했다.
한편 이날 방송되는 SBS ‘정글의 법칙‘에서는 아빠의 마지막 모습을 상상하는 시간을 가질 예정이다.
특히 아이 엄마를 둔 두 명의 미혼모의 이야기를 듣게 된다.
이어 아빠의 마지막 면모를 엿볼 수 있는 시간이 있을 예정이다. 이번 포럼에선 중국 칭다오 국제무역센터, 홍콩무역센터, 서울무역센터 등 수출유망 무역관에 진출한 중국 바이어 150여명이 참석한 가운데 중국 진출을 희망하는 한국 기업지원기관들의 현장방문과 수출상담회를 개최했다.
한국무역센터와 무역협회는 이날 중국 바이어를 대상으로 비즈니스 상담과 수출상담회, 기업간 자매결연 체결 등으로 매칭상담회를 개최하고 중국 진출업체들과 1대1 개별상담을 진행하여 우수제품에 대한 수출 상담과 구매성사까지 함께 이뤄졌다.
이날 포럼 참석차 방한한 샨타 화베트남무역


In [3]:
# Use a pipeline as a high-level helper
from transformers import pipeline
pipe = pipeline("text-generation", model="heegyu/polyglot-ko-1.3b-chat", device=0) ### ... 이 부분을 완성하시오

RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

In [2]:
sent = "건강한 몸을 만들기 위해서는"
generated_text = pipe(sent, max_new_tokens=256)
print(generated_text[0]['generated_text'])

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

In [ ]:
sent = "건강한 몸을 만들기 위해서는"
generated_text = pipe(sent, max_new_tokens=256, eos_token_id=2, pad_token_id=2)
print(generated_text[0]['generated_text'])

In [ ]:
chat_sent = '건강한 몸을 만들기 위해서는 어떻게 해야 돼?'
prompt = '당신은 AI 챗봇입니다. 사용자에게 도움이 되고 유익한 내용을 제공해야 합니다. 답변은 길고 자세하며 친절한 설명을 덧붙여서 작성하세요.'
generated_text = pipe(f"{prompt}\n\n### 사용자: {chat_sent}\n\n### 챗봇:", max_new_tokens=256, eos_token_id=2, pad_token_id=2)
print(generated_text[0]['generated_text'])

In [ ]:
print(generated_text[0]['generated_text'].split('### 챗봇:')[1])